# Generated by Django 5.2.5 on 2025-09-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='evento',
            field=models.CharField(max_length=50),
        ),
    ]
