# Generated by Django 5.2.5 on 2025-09-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('pagos', '0002_alter_pago_estado_alter_pago_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='referencia',
        ),
        migrations.AddField(
            model_name='pago',
            name='carrito_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pe', 'Pendiente'), ('ap', 'Aprobado'), ('re', 'Rechazado')], max_length=2),
        ),
    ]
