# Generated by Django 5.2.5 on 2025-09-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
