# Generated by Django 5.2.5 on 2025-09-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_cupon_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
