# Generated by Django 5.2.5 on 2025-10-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_cupon_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carrito.cupon'),
        ),
    ]
