# Generated by Django 5.2.5 on 2025-09-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_favorito_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
